- hosts: all

  tasks:
  - name: Adding a repository for docker
    yum_repository:
            name: docker23
            description: Docker Repo
            baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
            gpgcheck: no

  - name: Install python3
    package:
        name: python3
        state: present

  - name: Install docker sdk
    command: "pip3 install docker"

  - name: Install Docker package
    yum:
     name: docker-ce-18.09.1-3.el7.x86_64
     enablerepo: Docker23
     state: present
     skip_broken: yes

  - name: Starting service
    service:
        name: "docker"
        state: started
        enabled: yes
    register: x

  - debug:
          var: x

  - name: create file
    file:
            path: "/Ansible"
            state: directory

  - name: transfer file
    copy:
            src: "/Ansible/basic.html"
            dest: "/var/www/html/"

  - name: image
    docker_image:
            name: httpd
            source: pull

  - name: create docker container
    docker_container:
           name: "myweb"
           image: "httpd"
           state: started
           ports:
           - "8080:80"
           volumes:
            - /Ansible/basic.html:/usr/local/apache2/htdocs/

    register: container_status

  - debug:
          var: container_status

